### ISSUE TITLE
Motivasiya

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Zohrab039/PragmatechFrontEndProject#1]
Bu şəkil bəlkə yazdıqlarını GitHuba push etməyinə kömək edər.

![GitHub contribution graph](https://i.postimg.cc/0jmJpjy8/IMG-20211125-122929-01.jpg)

**Comment by Zohrab039** [comment]
20 saniyə sırf heçnə demədən gözüm bərəli şəklə baxılı qaldm 😳 qısaca belə

**Comment by isbendiyarovanezrin** [comment]
O 20 saniyədən sonra bir **push** gəlmədisə mən də qısaca 🤐 belə olacam artıq haha

**Comment by Zohrab039** [comment]
Müəllim o qədər tapşırıq verib ki VSCode'a ancaq example yazmaq üçün
girirəm😢
